# -*- coding: utf-8 -*-
"""dummyData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-A-cJlpRSJsqigd3CXpTrP-xugLt7tNP
"""

import pandas as pd
import numpy as np
import uuid
import gspread
import time
from google.colab import auth
from google.auth import default

# Authenticate with Google Sheets
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# Open or create a Google Sheet
spreadsheet_name = "Threat Scoring Dataset"
try:
    sh = gc.open(spreadsheet_name)
except gspread.exceptions.SpreadsheetNotFound:
    sh = gc.create(spreadsheet_name)
    sh.share('pawarsrushti25804@gmail.com', perm_type='user', role='writer')

worksheet = sh.sheet1

# Function to generate new dummy data entry
def generate_dummy_entry():
    return [
        np.random.uniform(0.1, 100.0),  # Duration
        np.random.choice(["TCP", "UDP", "ICMP"]),  # Protocol
        f"192.168.1.{np.random.randint(1, 255)}",  # SourceIP
        f"10.0.0.{np.random.randint(1, 255)}",  # DestinationIP
        np.random.randint(1024, 65535),  # SourcePort
        np.random.randint(1024, 65535),  # DestinationPort
        np.random.randint(1, 1000),  # PacketCount
        np.random.randint(100, 100000),  # ByteCount
        np.random.choice(["Normal", "Attack"])  # Label
    ]

# Continuous data generation loop
while True:
    new_entry = generate_dummy_entry()
    worksheet.append_row(new_entry)
    print("New data appended to Google Sheets.")
    time.sleep(600)